<?php

namespace App\Http\Controllers;

use App\Models\TaskAssignee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;

class GuruTaskController extends Controller
{
    /**
     * Get tasks assigned to the current guru
     */
    public function index(Request $request)
    {
        $user = $request->user();

        // Get assignees for this user with related task
        $assignees = TaskAssignee::with('task')
            ->where('user_id', $user->id)
            ->latest()
            ->get();

        return response()->json([
            'status' => 'success',
            'data' => $assignees
        ]);
    }

    /**
     * Submit a task
     */
    public function submit(Request $request, TaskAssignee $assignee)
    {
        // Verify ownership
        if ($assignee->user_id !== $request->user()->id) {
            return response()->json([
                'status' => 'error',
                'message' => 'Unauthorized'
            ], 403);
        }

        // Validate based on task type
        // Use $assignee->task to check type
        $assignee->load('task');
        $task = $assignee->task;

        if (!$task) {
            return response()->json(['status' => 'error', 'message' => 'Task not found'], 404);
        }

        if ($task->type === 'upload') {
            $request->validate([
                'file' => 'required|file|mimes:pdf,doc,docx,jpg,jpeg,png,zip|max:10240', // 10MB
            ]);
        } elseif ($task->type === 'text') {
            $request->validate([
                'submission_content' => 'required|string',
            ]);
        }

        try {
            if ($task->type === 'upload') {
                if ($request->hasFile('file')) {
                    $path = $request->file('file')->store('task_submissions', 'public');
                    // Store full URL or relative path? 
                    // Usually relative path is stored in DB, accessible via storage link.
                    // But frontend expects URL to download.
                    // Let's store relative path, and backend resource/model accessor can handle URL, 
                    // or storing full URL if we use S3/Cloudinary.
                    // Here 'public' disk -> storage/app/public/....
                    // Access via asset('storage/...')

                    // Note: 'storage:link' command connects public/storage to storage/app/public.
                    // I will store the URL generated by Storage facade if possible, or just the path and use an accessor.
                    // To keep it simple for now, I'll store the relative path, but return the URL in response.

                    $assignee->submission_file = $path;
                }
            } elseif ($task->type === 'text') {
                $assignee->submission_content = $request->submission_content;
            } elseif ($task->type === 'simple') {
                $assignee->submission_content = 'Done';
            }

            $assignee->status = 'submitted';
            $assignee->submitted_at = now();
            // Reset feedback if re-submitting
            $assignee->admin_feedback = null;
            $assignee->save();

            return response()->json([
                'status' => 'success',
                'message' => 'Task submitted successfully',
                'data' => $assignee
            ]);

        } catch (\Exception $e) {
            Log::error('Task Submission Error: ' . $e->getMessage());
            return response()->json([
                'status' => 'error',
                'message' => 'Failed to submit task'
            ], 500);
        }
    }
}
